catalog:
  # Build tooling - shared across publishable packages
  typescript: ^5.7.3
  esbuild: ^0.23.0

  # Type definitions
  '@types/node': ^22.10.10

packages:
  - 'packages/*'
  - 'starters/*'
  - 'apps/*'
