catalog:
  # Build tooling - shared across publishable packages
  typescript: ^5.7.2
  esbuild: ^0.23.0

  # Type definitions
  '@types/node': ^20.14.11

packages:
  - 'packages/*'
  - 'starters/*'
  - 'apps/*'
