import { Suspense } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Container from "@/components/ui/Container";
import Footer from "@/components/ui/Footer";
import Header from "@/components/ui/Header";
import NavigationEvents from "@/components/helpers/navigationEvents";

import "./globals.css";
import "./preview.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getEnvironment(): string {
  return process.env.ENVIRONMENT || "production";
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const environment = getEnvironment();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>
          <Header />
          {children}
          <Footer />
        </Container>
        <Suspense fallback={null}>
          <NavigationEvents environment={environment} />
        </Suspense>
      </body>
    </html>
  );
}
