/* eslint-disable */
/* prettier-ignore */
import type { TadaDocumentNode, $tada } from 'gql.tada';

declare module 'gql.tada' {
 interface setupCache {
    "\n  fragment ImageFragment on Image {\n    url\n    width\n    height\n    alt\n    title\n  }\n":
      TadaDocumentNode<{ title: string | null; alt: string | null; height: number; width: number; url: string; }, {}, { fragment: "ImageFragment"; on: "Image"; masked: true; }>;
    "\n  fragment MediaImageFragment on MediaImage {\n    id\n    mediaImage {\n      ...ImageFragment\n    }\n  }\n":
      TadaDocumentNode<{ mediaImage: { [$tada.fragmentRefs]: { ImageFragment: "Image"; }; }; id: string; }, {}, { fragment: "MediaImageFragment"; on: "MediaImage"; masked: true; }>;
    "\n  fragment MetatagFragment on MetaTag @_unmask {\n    __typename\n    ... on MetaTagLink {\n      attributes {\n        rel\n        href\n      }\n    }\n    ... on MetaTagValue {\n      attributes {\n        name\n        content\n      }\n    }\n    ... on MetaTagProperty {\n      attributes {\n        property\n        content\n      }\n    }\n  }\n":
      TadaDocumentNode<{ attributes: { href: string | null; rel: string | null; }; __typename: "MetaTagLink"; } | { attributes: { content: string | null; property: string | null; }; __typename: "MetaTagProperty"; } | { attributes: { content: string | null; name: string | null; }; __typename: "MetaTagValue"; }, {}, { fragment: "MetatagFragment"; on: "MetaTag"; masked: false; }>;
    "\n  fragment LinkFragment on Link {\n    url\n    title\n    internal\n  }\n":
      TadaDocumentNode<{ internal: boolean; title: string | null; url: string | null; }, {}, { fragment: "LinkFragment"; on: "Link"; masked: true; }>;
    "\n  fragment TextFragment on Text {\n    format\n    value\n    processed\n  }\n":
      TadaDocumentNode<{ processed: unknown; value: string | null; format: string | null; }, {}, { fragment: "TextFragment"; on: "Text"; masked: true; }>;
    "\n  fragment UserFragment on User {\n    id\n    name\n    picture {\n      ... on MediaImage {\n        ...MediaImageFragment\n      }\n    }\n  }\n":
      TadaDocumentNode<{ picture: { __typename?: "MediaImage" | undefined; [$tada.fragmentRefs]: { MediaImageFragment: "MediaImage"; }; } | null; name: string; id: string; }, {}, { fragment: "UserFragment"; on: "User"; masked: true; }>;
    "\n  fragment ParagraphCodeBlockFragment on ParagraphCodeBlock {\n    __typename\n    id\n    titleOptional\n    code\n    language\n    showLineNumbers\n  }\n":
      TadaDocumentNode<{ showLineNumbers: boolean | null; language: string; code: string; titleOptional: string | null; id: string; __typename: "ParagraphCodeBlock"; }, {}, { fragment: "ParagraphCodeBlockFragment"; on: "ParagraphCodeBlock"; masked: true; }>;
    "\n  fragment ParagraphHeroCtaFragment on ParagraphHeroCta {\n    __typename\n    id\n    title\n    text\n    intro\n    cta {\n      ...LinkFragment\n    }\n  }\n ":
      TadaDocumentNode<{ cta: { [$tada.fragmentRefs]: { LinkFragment: "Link"; }; }[]; intro: string; text: string; title: string; id: string; __typename: "ParagraphHeroCta"; }, {}, { fragment: "ParagraphHeroCtaFragment"; on: "ParagraphHeroCta"; masked: true; }>;
    "\n  fragment ParagraphTextFragment on ParagraphText {\n    __typename\n    id\n    title\n    textRich {\n      ...TextFragment\n    }\n  }\n ":
      TadaDocumentNode<{ textRich: { [$tada.fragmentRefs]: { TextFragment: "Text"; }; }; title: string; id: string; __typename: "ParagraphText"; }, {}, { fragment: "ParagraphTextFragment"; on: "ParagraphText"; masked: true; }>;
    "\n  fragment ParagraphImageFragment on ParagraphImage {\n    __typename\n    id\n    image {\n      ...MediaImageFragment\n    }\n  }\n ":
      TadaDocumentNode<{ image: { __typename?: "MediaImage" | undefined; [$tada.fragmentRefs]: { MediaImageFragment: "MediaImage"; }; } | null; id: string; __typename: "ParagraphImage"; }, {}, { fragment: "ParagraphImageFragment"; on: "ParagraphImage"; masked: true; }>;
    "\n  fragment ParagraphHeroTextFragment on ParagraphHeroText {\n    __typename\n    id\n    intro\n    title\n    text\n  }\n ":
      TadaDocumentNode<{ text: string; title: string; intro: string; id: string; __typename: "ParagraphHeroText"; }, {}, { fragment: "ParagraphHeroTextFragment"; on: "ParagraphHeroText"; masked: true; }>;
    "\n  fragment ParagraphStaticComponentFragment on ParagraphStaticComponent {\n    __typename\n    id\n    component\n  }\n":
      TadaDocumentNode<{ component: string | null; id: string; __typename: "ParagraphStaticComponent"; }, {}, { fragment: "ParagraphStaticComponentFragment"; on: "ParagraphStaticComponent"; masked: true; }>;
    "\nfragment ParagraphViewReference on ParagraphViewReference {\n  __typename\n  id\n  reference {\n    __typename\n    ... on ViewBlogTeaserResult {\n      id\n      view\n      display \n      results {\n        # @todo fix use of NodeArticleTeaserFragment\n        # ...NodeArticleTeaserFragment\n        ... on NodeArticle {\n          __typename\n          id\n          title\n          summary\n          path\n          image {\n            ...MediaImageFragment\n          }\n          author {\n            ...UserFragment\n          }\n        }\n      }\n    }\n  }\n}\n":
      TadaDocumentNode<{ reference: { results: ({ author: { [$tada.fragmentRefs]: { UserFragment: "User"; }; } | null; image: { __typename?: "MediaImage" | undefined; [$tada.fragmentRefs]: { MediaImageFragment: "MediaImage"; }; }; path: string; summary: string; title: string; id: string; __typename: "NodeArticle"; } | { __typename?: "NodePage" | undefined; })[]; display: string; view: string; id: string; __typename: "ViewBlogTeaserResult"; }; id: string; __typename: "ParagraphViewReference"; }, {}, { fragment: "ParagraphViewReference"; on: "ParagraphViewReference"; masked: true; }>;
    "\n  fragment ParagraphUnionFragment on ParagraphUnion {\n    ... on ParagraphInterface {\n      __typename\n      id\n    }\n    ...ParagraphCodeBlockFragment\n    ...ParagraphHeroCtaFragment\n    ...ParagraphTextFragment\n    ...ParagraphImageFragment\n    ...ParagraphHeroTextFragment\n    ...ParagraphStaticComponentFragment\n    ...ParagraphViewReference\n  }\n":
      TadaDocumentNode<{ id: string; __typename: "ParagraphCodeBlock"; [$tada.fragmentRefs]: { ParagraphCodeBlockFragment: "ParagraphCodeBlock"; }; } | { id: string; __typename: "ParagraphHeroCta"; [$tada.fragmentRefs]: { ParagraphHeroCtaFragment: "ParagraphHeroCta"; }; } | { id: string; __typename: "ParagraphHeroText"; [$tada.fragmentRefs]: { ParagraphHeroTextFragment: "ParagraphHeroText"; }; } | { id: string; __typename: "ParagraphImage"; [$tada.fragmentRefs]: { ParagraphImageFragment: "ParagraphImage"; }; } | { id: string; __typename: "ParagraphStaticComponent"; [$tada.fragmentRefs]: { ParagraphStaticComponentFragment: "ParagraphStaticComponent"; }; } | { id: string; __typename: "ParagraphText"; [$tada.fragmentRefs]: { ParagraphTextFragment: "ParagraphText"; }; } | { id: string; __typename: "ParagraphViewReference"; [$tada.fragmentRefs]: { ParagraphViewReference: "ParagraphViewReference"; }; }, {}, { fragment: "ParagraphUnionFragment"; on: "ParagraphUnion"; masked: true; }>;
    "\n  fragment NodePageFragment on NodePage  {\n    __typename\n    id\n    title\n    showTitle\n    summary\n    image {\n      ...MediaImageFragment\n    }\n    metatag {\n      ...MetatagFragment\n    }\n    components {\n      ...ParagraphUnionFragment\n    }\n  }\n":
      TadaDocumentNode<{ components: ({ __typename?: "ParagraphCodeBlock" | undefined; [$tada.fragmentRefs]: { ParagraphUnionFragment: "ParagraphUnion"; }; } | { __typename?: "ParagraphHeroCta" | undefined; [$tada.fragmentRefs]: { ParagraphUnionFragment: "ParagraphUnion"; }; } | { __typename?: "ParagraphHeroText" | undefined; [$tada.fragmentRefs]: { ParagraphUnionFragment: "ParagraphUnion"; }; } | { __typename?: "ParagraphImage" | undefined; [$tada.fragmentRefs]: { ParagraphUnionFragment: "ParagraphUnion"; }; } | { __typename?: "ParagraphStaticComponent" | undefined; [$tada.fragmentRefs]: { ParagraphUnionFragment: "ParagraphUnion"; }; } | { __typename?: "ParagraphText" | undefined; [$tada.fragmentRefs]: { ParagraphUnionFragment: "ParagraphUnion"; }; } | { __typename?: "ParagraphViewReference" | undefined; [$tada.fragmentRefs]: { ParagraphUnionFragment: "ParagraphUnion"; }; })[] | null; metatag: ({ attributes: { href: string | null; rel: string | null; }; __typename: "MetaTagLink"; } | { attributes: { content: string | null; property: string | null; }; __typename: "MetaTagProperty"; } | { attributes: { content: string | null; name: string | null; }; __typename: "MetaTagValue"; })[]; image: { __typename?: "MediaImage" | undefined; [$tada.fragmentRefs]: { MediaImageFragment: "MediaImage"; }; }; summary: string; showTitle: boolean | null; title: string; id: string; __typename: "NodePage"; }, {}, { fragment: "NodePageFragment"; on: "NodePage"; masked: true; }>;
    "\n  fragment NodeArticleFragment on NodeArticle {\n    __typename\n    id\n    title\n    summary\n    path\n    image {\n      ...MediaImageFragment\n    }\n    author {\n      ...UserFragment\n    }\n    metatag {\n      ...MetatagFragment\n    }\n    components {\n      ...ParagraphUnionFragment\n    }\n  }\n":
      TadaDocumentNode<{ components: ({ __typename?: "ParagraphCodeBlock" | undefined; [$tada.fragmentRefs]: { ParagraphUnionFragment: "ParagraphUnion"; }; } | { __typename?: "ParagraphHeroCta" | undefined; [$tada.fragmentRefs]: { ParagraphUnionFragment: "ParagraphUnion"; }; } | { __typename?: "ParagraphHeroText" | undefined; [$tada.fragmentRefs]: { ParagraphUnionFragment: "ParagraphUnion"; }; } | { __typename?: "ParagraphImage" | undefined; [$tada.fragmentRefs]: { ParagraphUnionFragment: "ParagraphUnion"; }; } | { __typename?: "ParagraphStaticComponent" | undefined; [$tada.fragmentRefs]: { ParagraphUnionFragment: "ParagraphUnion"; }; } | { __typename?: "ParagraphText" | undefined; [$tada.fragmentRefs]: { ParagraphUnionFragment: "ParagraphUnion"; }; } | { __typename?: "ParagraphViewReference" | undefined; [$tada.fragmentRefs]: { ParagraphUnionFragment: "ParagraphUnion"; }; })[] | null; metatag: ({ attributes: { href: string | null; rel: string | null; }; __typename: "MetaTagLink"; } | { attributes: { content: string | null; property: string | null; }; __typename: "MetaTagProperty"; } | { attributes: { content: string | null; name: string | null; }; __typename: "MetaTagValue"; })[]; author: { [$tada.fragmentRefs]: { UserFragment: "User"; }; } | null; image: { __typename?: "MediaImage" | undefined; [$tada.fragmentRefs]: { MediaImageFragment: "MediaImage"; }; }; path: string; summary: string; title: string; id: string; __typename: "NodeArticle"; }, {}, { fragment: "NodeArticleFragment"; on: "NodeArticle"; masked: true; }>;
    "\n  fragment NodeArticleTeaserFragment on NodeArticle {\n    __typename\n    id\n    title\n    summary\n    path\n    image {\n      ...MediaImageFragment\n    }\n    author {\n      ...UserFragment\n    }\n  }\n":
      TadaDocumentNode<{ author: { [$tada.fragmentRefs]: { UserFragment: "User"; }; } | null; image: { __typename?: "MediaImage" | undefined; [$tada.fragmentRefs]: { MediaImageFragment: "MediaImage"; }; }; path: string; summary: string; title: string; id: string; __typename: "NodeArticle"; }, {}, { fragment: "NodeArticleTeaserFragment"; on: "NodeArticle"; masked: true; }>;
    "\n  fragment TermTagsFragment on TermTags  {\n    __typename\n    id\n    name\n    description {\n      processed\n    }\n  }\n":
      TadaDocumentNode<{ description: { processed: unknown; }; name: string; id: string; __typename: "TermTags"; }, {}, { fragment: "TermTagsFragment"; on: "TermTags"; masked: true; }>;
    "\n      query route($path: String!) {\n        route(path: $path) {\n          __typename\n          ... on RouteInternal {\n            entity {\n              __typename\n              ... on NodePage {\n                id\n                title\n              }\n              ...NodePageFragment\n              ...NodeArticleFragment\n              ...TermTagsFragment\n            }\n          }\n        }\n      }\n    ":
      TadaDocumentNode<{ route: { __typename: "RouteExternal"; } | { entity: { __typename: "MediaImage"; } | { __typename: "NodeArticle"; [$tada.fragmentRefs]: { NodeArticleFragment: "NodeArticle"; }; } | { title: string; id: string; __typename: "NodePage"; [$tada.fragmentRefs]: { NodePageFragment: "NodePage"; }; } | { __typename: "TermTags"; [$tada.fragmentRefs]: { TermTagsFragment: "TermTags"; }; } | null; __typename: "RouteInternal"; } | { __typename: "RouteRedirect"; } | null; }, { path: string; }, void>;
  }
}
