export * from './ParagraphCardGroupResolver'
export * from './ParagraphHeroResolver'
export * from './ParagraphStaticComponentResover'
export * from './ParagraphViewReferenceResolver'
export * from './ParagraphCtaResolver'
export * from './ParagraphFaqResolver'
export * from './ParagraphLogoGroupResolver'
export * from './ParagraphTestimonialResolver'
